//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuseumWpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OuterAction
    {
        public int ID { get; set; }
        public Nullable<int> set_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public int company_id { get; set; }
        public int exhibition_id { get; set; }
        public string description { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Exhibition Exhibition { get; set; }
        public virtual Item Item { get; set; }
        public virtual Set Set { get; set; }
    }
}
